version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
    env_file:
      - .env  # <-- Thêm dòng này để NestJS đọc được .env nếu app có dùng @nestjs/config
    environment:
      DB_HOST: db           # Không nên là 'localhost' → phải là tên service trong Docker network
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
